name: test-action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test local action
        id: test-action
        uses: ./
        with:
          file: ./test/go.mod
      - name: Print output
        run: |
          echo "go=${{ steps.test-action.outputs.go }} toolchain=${{ steps.test-action.outputs.toolchain }} toolchain-go-version=${{ steps.test-action.outputs.toolchain-go-version }}"
