name: test-action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test local action
        id: parse-gomod
        uses: ./
        with:
          file: ./test/go.mod
      - name: Print output
        run: |
          echo "go=${{ steps.parse-gomod.outputs.go }} toolchain=${{ steps.parse-gomod.outputs.toolchain }} toolchain-go-version=${{ steps.parse-gomod.outputs.toolchain-go-version }}"
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.parse-gomod.outputs.toolchain-go-version }}
          cache: false
      - name: Print installed go version
        run: |
          go version
